spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/todo
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful

logging:
  file:
    path: logs


--- #local
spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/todo
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update


--- #dev
spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver  # correctly configure
    url: jdbc:mysql://dev-somewhere.ap-northeast-2.rds.amazonaws.com:3306/dev-db
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev


--- #prod
spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver # correctly configure
    url: jdbc:mysql://prod-somewhere.ap-northeast-2.rds.amazonaws.com:3306/prod-db
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: validate
  config:
    activate:
      on-profile: prod