name: Deploy Todo API Server
on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Backend Continous Integration
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
        working-directory: ${{ env.working-directory }}

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/baackend/.gradle/caches
            ~/backend/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew clean build -x=jar
        shell: bash
        working-directory: ${{ env.working-directory }}

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: dev
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: dev
          status: FAILED
          color: danger